### ISSUE TITLE
No such file or directory: 'version.txt'

### ISSUE THREAD

**Issue by Jonii** [atw1020/sente#90]
With Python 3.11, in a Conda environment, I get this:

```
$ pip install sente
Collecting sente
  Using cached sente-0.4.2.tar.gz (6.1 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-zeg2uwrv/sente_c6b6c3dd27b84e27b21796071647bc83/setup.py", line 135, in <module>
          version=read_file("version.txt").strip(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-zeg2uwrv/sente_c6b6c3dd27b84e27b21796071647bc83/setup.py", line 128, in read_file
          with open(filename, encoding="utf-8") as file:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'version.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

The file, used by setup.py, is not included within the package served for example here: https://pypi.org/project/sente/#files so to me it seems like this is just a problem of file not being included by accident.

**Comment by divenal** [comment]
Just had the same issue on python 3.11
Worked okay with python 3.9 though

**Comment by fishcu** [comment]
Same issue here.

**Comment by gezabohus** [comment]
Same issue here.
